sudo: required
services:
  - docker

before_install:
  - docker build -t davidcorney/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true davidcorney/react-test npm test

after_success:
  - docker build -t davidcorney/multi-client ./client
  - docker build -t davidcorney/multi-nginx ./nginx
  - docker build -t davidcorney/multi-server ./server
  - docker build -t davidcorney/multi-worker ./worker
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push davidcorney/multi-client
  - docker push davidcorney/multi-nginx
  - docker push davidcorney/multi-server
  - docker push davidcorney/multi-worker
